### ISSUE TITLE
範例網頁錯誤

### ISSUE THREAD

**Issue by swrdism** [lin826/Github.io-Practice#1]
使用：我們在桃園市中壢區中大路300號見
1.已經輸入的字數沒有改變
2.沒有抓到地址

**Comment by lin826** [comment]
源自 Google Chrome 瀏覽器，避免載入不安全的指令碼。
解決辦法：點選網址列右方圖示，點擊「載入不安全的指令碼」。

**Comment by lin826** [comment]
發現原因：使用 JQuery 版本過舊，更新後問題解決。
